# Generated by Django 3.0.5 on 2020-07-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='bank_details',
        ),
    ]
