# Generated by Django 3.0.5 on 2020-07-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_app', '0002_auto_20200701_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank_details',
            new_name='bank_detail',
        ),
    ]
